

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class HRMEntities : DbContext
{
    public HRMEntities()
        : base("name=HRMEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tblAssesmentQuestDetails> tblAssesmentQuestDetails { get; set; }

    public virtual DbSet<tblAssQuestMas> tblAssQuestMas { get; set; }

    public virtual DbSet<tblCertificateCodeMas> tblCertificateCodeMas { get; set; }

    public virtual DbSet<tblCity> tblCity { get; set; }

    public virtual DbSet<tblConsultantDocDetail> tblConsultantDocDetail { get; set; }

    public virtual DbSet<tblConsultantLedgerDetail> tblConsultantLedgerDetail { get; set; }

    public virtual DbSet<tblConsultantSlipDetail> tblConsultantSlipDetail { get; set; }

    public virtual DbSet<tblConversation> tblConversation { get; set; }

    public virtual DbSet<tblCurrentExpDetail> tblCurrentExpDetail { get; set; }

    public virtual DbSet<tblDeptMas> tblDeptMas { get; set; }

    public virtual DbSet<tblDesignationMas> tblDesignationMas { get; set; }

    public virtual DbSet<tblDesiQualification> tblDesiQualification { get; set; }

    public virtual DbSet<tblDesiSetting> tblDesiSetting { get; set; }

    public virtual DbSet<tblDocDetails> tblDocDetails { get; set; }

    public virtual DbSet<tblDocMas> tblDocMas { get; set; }

    public virtual DbSet<tblDoctorDocMas> tblDoctorDocMas { get; set; }

    public virtual DbSet<tblDoctorUploadDetail> tblDoctorUploadDetail { get; set; }

    public virtual DbSet<tblDocTypeMas> tblDocTypeMas { get; set; }

    public virtual DbSet<tblEmpAssesmentDetails> tblEmpAssesmentDetails { get; set; }

    public virtual DbSet<tblEmpAssesmentMas> tblEmpAssesmentMas { get; set; }

    public virtual DbSet<tblEmpCodeMas> tblEmpCodeMas { get; set; }

    public virtual DbSet<tblEmpDetails> tblEmpDetails { get; set; }

    public virtual DbSet<tblEMpExitDetail> tblEMpExitDetail { get; set; }

    public virtual DbSet<tblEmpExitMas> tblEmpExitMas { get; set; }

    public virtual DbSet<tblEmpLoginUser> tblEmpLoginUser { get; set; }

    public virtual DbSet<tblEmpMas> tblEmpMas { get; set; }

    public virtual DbSet<tblExitInterviewQuestMas> tblExitInterviewQuestMas { get; set; }

    public virtual DbSet<tblExperienceDetail> tblExperienceDetail { get; set; }

    public virtual DbSet<tblExperienceMas> tblExperienceMas { get; set; }

    public virtual DbSet<tblGroupMaster> tblGroupMaster { get; set; }

    public virtual DbSet<tblIntershipDetail> tblIntershipDetail { get; set; }

    public virtual DbSet<tblIntershipMas> tblIntershipMas { get; set; }

    public virtual DbSet<tblJoiningRemarks> tblJoiningRemarks { get; set; }

    public virtual DbSet<tblKRADocDetail> tblKRADocDetail { get; set; }

    public virtual DbSet<tblLeaveBalance> tblLeaveBalance { get; set; }

    public virtual DbSet<tblLedgerSession> tblLedgerSession { get; set; }

    public virtual DbSet<tblLetterAppointDetail> tblLetterAppointDetail { get; set; }

    public virtual DbSet<tblLetterAppointMas> tblLetterAppointMas { get; set; }

    public virtual DbSet<tblLetterNumberMas> tblLetterNumberMas { get; set; }

    public virtual DbSet<tblLetterOfferDetail> tblLetterOfferDetail { get; set; }

    public virtual DbSet<tblLetterOfferMas> tblLetterOfferMas { get; set; }

    public virtual DbSet<tblManPowerDetail> tblManPowerDetail { get; set; }

    public virtual DbSet<tblManPowerMas> tblManPowerMas { get; set; }

    public virtual DbSet<tblMonthMaster> tblMonthMaster { get; set; }

    public virtual DbSet<tblMouDetail> tblMouDetail { get; set; }

    public virtual DbSet<tblOtherDocDetail> tblOtherDocDetail { get; set; }

    public virtual DbSet<tblOtherDocumentMas> tblOtherDocumentMas { get; set; }

    public virtual DbSet<tblPayrollData> tblPayrollData { get; set; }

    public virtual DbSet<tblPermissionMaster> tblPermissionMaster { get; set; }

    public virtual DbSet<tblPosDesiMap> tblPosDesiMap { get; set; }

    public virtual DbSet<tblPosDocMap> tblPosDocMap { get; set; }

    public virtual DbSet<tblPositionCategoryMas> tblPositionCategoryMas { get; set; }

    public virtual DbSet<tblQualiDetails> tblQualiDetails { get; set; }

    public virtual DbSet<tblQualiMas> tblQualiMas { get; set; }

    public virtual DbSet<tblQuraterMas> tblQuraterMas { get; set; }

    public virtual DbSet<tblRegistrationDetail> tblRegistrationDetail { get; set; }

    public virtual DbSet<tblRequisition> tblRequisition { get; set; }

    public virtual DbSet<tblRequisitionNumberMas> tblRequisitionNumberMas { get; set; }

    public virtual DbSet<tblSalaryIncrement> tblSalaryIncrement { get; set; }

    public virtual DbSet<tblSkillMarksAndPositionMappMas> tblSkillMarksAndPositionMappMas { get; set; }

    public virtual DbSet<tblState> tblState { get; set; }

    public virtual DbSet<tblTitleMas> tblTitleMas { get; set; }

    public virtual DbSet<tblTransferDetail> tblTransferDetail { get; set; }

    public virtual DbSet<tblUserAuthorize> tblUserAuthorize { get; set; }

    public virtual DbSet<tblUserLove> tblUserLove { get; set; }

    public virtual DbSet<tblUserMaster> tblUserMaster { get; set; }

    public virtual DbSet<tblUserPermission> tblUserPermission { get; set; }

    public virtual DbSet<tblVPForward> tblVPForward { get; set; }

    public virtual DbSet<tblConsultantSlips> tblConsultantSlips { get; set; }

    public virtual DbSet<tblLeaveApplication> tblLeaveApplication { get; set; }

    public virtual DbSet<tblLeaveApplicationDetail> tblLeaveApplicationDetail { get; set; }

    public virtual DbSet<tblLeaveType> tblLeaveType { get; set; }

    public virtual DbSet<tblConsultantTDS> tblConsultantTDS { get; set; }

    public virtual DbSet<TblDnbFeeStructure> TblDnbFeeStructure { get; set; }

    public virtual DbSet<TblDnbStudent> TblDnbStudent { get; set; }

    public virtual DbSet<TblDnbFeeSubmission> TblDnbFeeSubmission { get; set; }

    public virtual DbSet<tblYearMaster> tblYearMaster { get; set; }


    public virtual ObjectResult<spCurrentExpCertificate_Result> spCurrentExpCertificate(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCurrentExpCertificate_Result>("spCurrentExpCertificate", idParameter);
    }


    public virtual ObjectResult<spEditPosDesiMap_Result> spEditPosDesiMap(Nullable<int> fk_pos_id)
    {

        var fk_pos_idParameter = fk_pos_id.HasValue ?
            new ObjectParameter("fk_pos_id", fk_pos_id) :
            new ObjectParameter("fk_pos_id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEditPosDesiMap_Result>("spEditPosDesiMap", fk_pos_idParameter);
    }


    public virtual ObjectResult<spEditPosDocMap_Result> spEditPosDocMap(Nullable<int> fk_pos_id)
    {

        var fk_pos_idParameter = fk_pos_id.HasValue ?
            new ObjectParameter("fk_pos_id", fk_pos_id) :
            new ObjectParameter("fk_pos_id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEditPosDocMap_Result>("spEditPosDocMap", fk_pos_idParameter);
    }


    public virtual ObjectResult<spEmpAppointLetter_Result> spEmpAppointLetter(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEmpAppointLetter_Result>("spEmpAppointLetter", idParameter);
    }


    public virtual ObjectResult<spEmpExpLetter_Result> spEmpExpLetter(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEmpExpLetter_Result>("spEmpExpLetter", idParameter);
    }


    public virtual ObjectResult<spEmpinternshipLetter_Result> spEmpinternshipLetter(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEmpinternshipLetter_Result>("spEmpinternshipLetter", idParameter);
    }


    public virtual ObjectResult<spEmpOfferLetter_Result> spEmpOfferLetter(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEmpOfferLetter_Result>("spEmpOfferLetter", idParameter);
    }


    public virtual int spGetActiveConsultant(Nullable<int> code)
    {

        var codeParameter = code.HasValue ?
            new ObjectParameter("Code", code) :
            new ObjectParameter("Code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetActiveConsultant", codeParameter);
    }


    public virtual ObjectResult<spGetAssesmentRemarks_Result> spGetAssesmentRemarks(Nullable<int> fk_empid, Nullable<int> intcode)
    {

        var fk_empidParameter = fk_empid.HasValue ?
            new ObjectParameter("fk_empid", fk_empid) :
            new ObjectParameter("fk_empid", typeof(int));


        var intcodeParameter = intcode.HasValue ?
            new ObjectParameter("intcode", intcode) :
            new ObjectParameter("intcode", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAssesmentRemarks_Result>("spGetAssesmentRemarks", fk_empidParameter, intcodeParameter);
    }


    public virtual ObjectResult<spGetCohort_Result> spGetCohort(string monthName, Nullable<int> empid, Nullable<int> fkDeptid)
    {

        var monthNameParameter = monthName != null ?
            new ObjectParameter("monthName", monthName) :
            new ObjectParameter("monthName", typeof(string));


        var empidParameter = empid.HasValue ?
            new ObjectParameter("empid", empid) :
            new ObjectParameter("empid", typeof(int));


        var fkDeptidParameter = fkDeptid.HasValue ?
            new ObjectParameter("fkDeptid", fkDeptid) :
            new ObjectParameter("fkDeptid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCohort_Result>("spGetCohort", monthNameParameter, empidParameter, fkDeptidParameter);
    }


    public virtual ObjectResult<spGetConsultant_Result> spGetConsultant(Nullable<int> code)
    {

        var codeParameter = code.HasValue ?
            new ObjectParameter("Code", code) :
            new ObjectParameter("Code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetConsultant_Result>("spGetConsultant", codeParameter);
    }


    public virtual ObjectResult<spGetConsultantSlip_Result> spGetConsultantSlip(Nullable<System.Guid> uID)
    {

        var uIDParameter = uID.HasValue ?
            new ObjectParameter("UID", uID) :
            new ObjectParameter("UID", typeof(System.Guid));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetConsultantSlip_Result>("spGetConsultantSlip", uIDParameter);
    }


    public virtual ObjectResult<spGetConsultantSlipDetail_Result> spGetConsultantSlipDetail(Nullable<System.Guid> uID)
    {

        var uIDParameter = uID.HasValue ?
            new ObjectParameter("UID", uID) :
            new ObjectParameter("UID", typeof(System.Guid));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetConsultantSlipDetail_Result>("spGetConsultantSlipDetail", uIDParameter);
    }


    public virtual ObjectResult<spGetDeptMapping_Result> spGetDeptMapping(Nullable<int> id, Nullable<int> code)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        var codeParameter = code.HasValue ?
            new ObjectParameter("code", code) :
            new ObjectParameter("code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDeptMapping_Result>("spGetDeptMapping", idParameter, codeParameter);
    }


    public virtual ObjectResult<spGetEmpData_Result> spGetEmpData(Nullable<int> id, Nullable<int> code)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        var codeParameter = code.HasValue ?
            new ObjectParameter("code", code) :
            new ObjectParameter("code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetEmpData_Result>("spGetEmpData", idParameter, codeParameter);
    }


    public virtual int spGetInternshipLetter(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetInternshipLetter", idParameter);
    }


    public virtual int spGetLeaveCounter(Nullable<int> empcode)
    {

        var empcodeParameter = empcode.HasValue ?
            new ObjectParameter("empcode", empcode) :
            new ObjectParameter("empcode", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetLeaveCounter", empcodeParameter);
    }


    public virtual int spGetOfferLetter(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetOfferLetter", idParameter);
    }


    public virtual ObjectResult<spGetPartialAuthorizedEmp_Result> spGetPartialAuthorizedEmp(Nullable<int> id, Nullable<int> code)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        var codeParameter = code.HasValue ?
            new ObjectParameter("code", code) :
            new ObjectParameter("code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetPartialAuthorizedEmp_Result>("spGetPartialAuthorizedEmp", idParameter, codeParameter);
    }


    public virtual ObjectResult<spGetRequisition_Result> spGetRequisition(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetRequisition_Result>("spGetRequisition", idParameter);
    }


    public virtual ObjectResult<spGetSearchEmployee_Result> spGetSearchEmployee(Nullable<int> code)
    {

        var codeParameter = code.HasValue ?
            new ObjectParameter("code", code) :
            new ObjectParameter("code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSearchEmployee_Result>("spGetSearchEmployee", codeParameter);
    }


    public virtual ObjectResult<spGetUserPermission_Result> spGetUserPermission(string vchUser, Nullable<int> code)
    {

        var vchUserParameter = vchUser != null ?
            new ObjectParameter("vchUser", vchUser) :
            new ObjectParameter("vchUser", typeof(string));


        var codeParameter = code.HasValue ?
            new ObjectParameter("code", code) :
            new ObjectParameter("code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUserPermission_Result>("spGetUserPermission", vchUserParameter, codeParameter);
    }


    public virtual ObjectResult<spLeaveReport_Result> spLeaveReport(Nullable<int> code, string sdate, string edate)
    {

        var codeParameter = code.HasValue ?
            new ObjectParameter("code", code) :
            new ObjectParameter("code", typeof(int));


        var sdateParameter = sdate != null ?
            new ObjectParameter("sdate", sdate) :
            new ObjectParameter("sdate", typeof(string));


        var edateParameter = edate != null ?
            new ObjectParameter("edate", edate) :
            new ObjectParameter("edate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLeaveReport_Result>("spLeaveReport", codeParameter, sdateParameter, edateParameter);
    }


    public virtual ObjectResult<spLeaveReport123_Result> spLeaveReport123(Nullable<int> code, string sdate, string edate)
    {

        var codeParameter = code.HasValue ?
            new ObjectParameter("code", code) :
            new ObjectParameter("code", typeof(int));


        var sdateParameter = sdate != null ?
            new ObjectParameter("sdate", sdate) :
            new ObjectParameter("sdate", typeof(string));


        var edateParameter = edate != null ?
            new ObjectParameter("edate", edate) :
            new ObjectParameter("edate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLeaveReport123_Result>("spLeaveReport123", codeParameter, sdateParameter, edateParameter);
    }


    public virtual ObjectResult<spGetdol_Result> spGetdol(string sdate, string edate, Nullable<int> code)
    {

        var sdateParameter = sdate != null ?
            new ObjectParameter("Sdate", sdate) :
            new ObjectParameter("Sdate", typeof(string));


        var edateParameter = edate != null ?
            new ObjectParameter("Edate", edate) :
            new ObjectParameter("Edate", typeof(string));


        var codeParameter = code.HasValue ?
            new ObjectParameter("Code", code) :
            new ObjectParameter("Code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetdol_Result>("spGetdol", sdateParameter, edateParameter, codeParameter);
    }


    public virtual ObjectResult<spGetBranchMapping_Result> spGetBranchMapping(Nullable<int> code)
    {

        var codeParameter = code.HasValue ?
            new ObjectParameter("code", code) :
            new ObjectParameter("code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetBranchMapping_Result>("spGetBranchMapping", codeParameter);
    }


    public virtual ObjectResult<spGetdoj123_Result> spGetdoj123(string sdate, string edate, Nullable<int> code)
    {

        var sdateParameter = sdate != null ?
            new ObjectParameter("Sdate", sdate) :
            new ObjectParameter("Sdate", typeof(string));


        var edateParameter = edate != null ?
            new ObjectParameter("Edate", edate) :
            new ObjectParameter("Edate", typeof(string));


        var codeParameter = code.HasValue ?
            new ObjectParameter("Code", code) :
            new ObjectParameter("Code", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetdoj123_Result>("spGetdoj123", sdateParameter, edateParameter, codeParameter);
    }


    public virtual ObjectResult<spGetConsumedLeave_Result> spGetConsumedLeave(Nullable<int> empcode)
    {

        var empcodeParameter = empcode.HasValue ?
            new ObjectParameter("empcode", empcode) :
            new ObjectParameter("empcode", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetConsumedLeave_Result>("spGetConsumedLeave", empcodeParameter);
    }


    public virtual ObjectResult<spGetConsumedConsultantLeave_Result> spGetConsumedConsultantLeave(Nullable<int> empcode)
    {

        var empcodeParameter = empcode.HasValue ?
            new ObjectParameter("empcode", empcode) :
            new ObjectParameter("empcode", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetConsumedConsultantLeave_Result>("spGetConsumedConsultantLeave", empcodeParameter);
    }


    public virtual ObjectResult<sp_GetDnbFeeReport_Result> sp_GetDnbFeeReport(Nullable<int> studentId, Nullable<int> yearNumber, string status)
    {

        var studentIdParameter = studentId.HasValue ?
            new ObjectParameter("StudentId", studentId) :
            new ObjectParameter("StudentId", typeof(int));


        var yearNumberParameter = yearNumber.HasValue ?
            new ObjectParameter("YearNumber", yearNumber) :
            new ObjectParameter("YearNumber", typeof(int));


        var statusParameter = status != null ?
            new ObjectParameter("Status", status) :
            new ObjectParameter("Status", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDnbFeeReport_Result>("sp_GetDnbFeeReport", studentIdParameter, yearNumberParameter, statusParameter);
    }

}

}

