//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndusCompanies
    {
        public int intPK { get; set; }
        public int ID { get; set; }
        public string descript { get; set; }
        public string DESCRIPT1 { get; set; }
        public string add1 { get; set; }
        public string add2 { get; set; }
        public string add3 { get; set; }
        public string add4 { get; set; }
        public string email { get; set; }
        public string itnum { get; set; }
        public string Lstnum { get; set; }
        public string istnum { get; set; }
        public string mnt { get; set; }
        public Nullable<System.DateTime> fdate { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string security { get; set; }
        public string suser { get; set; }
        public string pwd { get; set; }
        public Nullable<short> ses_code { get; set; }
        public string brep { get; set; }
        public string company_type { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string drep { get; set; }
        public string ss_name { get; set; }
        public string corp_id { get; set; }
        public string cperson { get; set; }
        public string cphone { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string Location { get; set; }
        public string UHIDPreFix { get; set; }
        public string isActive { get; set; }
        public Nullable<int> HeadOffice { get; set; }
        public string vchGSTNumber { get; set; }
    }
}
