//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    
    public partial class spGetdoj_Result123
    {
        public string vchName { get; set; }
        public string vchdeptname { get; set; }
        public string vchdesignation { get; set; }
        public bool bitIsReplacement { get; set; }
        public string vchRplcmntName { get; set; }
        public System.DateTime dtDOJ { get; set; }
        public int intsalary { get; set; }
        public string TempAddress { get; set; }
        public int intcode { get; set; }
        public string vchEmpFcode { get; set; }
        public string vchFatherName { get; set; }
        public string vchmothername { get; set; }
        public string TempState { get; set; }
        public string TempCity { get; set; }
        public Nullable<int> TempPin { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<int> Pin { get; set; }
        public string Address { get; set; }
        public System.DateTime dtDob { get; set; }
        public string Mstatus { get; set; }
        public string vchSex { get; set; }
        public string vchMobile { get; set; }
        public string vchAadharNo { get; set; }
        public string vchspouse { get; set; }
        public decimal decExperience { get; set; }
    }
}
