
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblAssesmentQuestDetails
{

    public int intid { get; set; }

    public int fk_userid { get; set; }

    public int fk_intEmpAssId { get; set; }

    public int fk_qid { get; set; }

    public string vchAnswer { get; set; }

    public string vchSpecialRemarks { get; set; }

    public Nullable<int> intTotal { get; set; }

    public string vchAssesmentBy { get; set; }

    public Nullable<System.DateTime> dtAssesment { get; set; }

    public string vchAssesmentHost { get; set; }

    public string vchAssesmentIpused { get; set; }

    public string vchAssUpdatedBy { get; set; }

    public Nullable<System.DateTime> dtAssUpdated { get; set; }

    public string vchAssUpdatedHost { get; set; }

    public string vchAssUpdatedIpused { get; set; }

    public Nullable<bool> BitIsSelected { get; set; }

    public Nullable<bool> BitIsCompleated { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }



    public virtual tblAssQuestMas tblAssQuestMas { get; set; }

    public virtual tblUserMaster tblUserMaster { get; set; }

}

}
