
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblAssQuestMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblAssQuestMas()
    {

        this.tblAssesmentQuestDetails = new HashSet<tblAssesmentQuestDetails>();

    }


    public int intqid { get; set; }

    public string vchQuestion { get; set; }

    public string vchAnsType { get; set; }

    public string vchcreatedby { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public string vchupdatedipused { get; set; }

    public string vchupdatedhostname { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public Nullable<bool> IsSelected { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAssesmentQuestDetails> tblAssesmentQuestDetails { get; set; }

}

}
