
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblCertificateCodeMas
{

    public int intid { get; set; }

    public string CertificateCode { get; set; }

    public Nullable<int> intstartFrom { get; set; }

    public Nullable<int> intCurrent { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> fk_TemplateId { get; set; }

    public Nullable<int> intYear { get; set; }

}

}
