
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblConsultantLedgerDetail
{

    public System.Guid UUID { get; set; }

    public int fk_EmpID { get; set; }

    public int intYear { get; set; }

    public int fk_LedgerMas { get; set; }

    public string vchFileName { get; set; }

    public string vchFileAddress { get; set; }

    public string vchDocMasName { get; set; }

    public Nullable<System.DateTime> dtUpload { get; set; }

    public string vchUpBy { get; set; }

    public int intCode { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpDatedBy { get; set; }

    public string vchCompareFile { get; set; }

    public string vchTempMasName { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
