
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblConsultantSlips
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblConsultantSlips()
    {

        this.tblConsultantSlipDetail = new HashSet<tblConsultantSlipDetail>();

    }


    public System.Guid UNid { get; set; }

    public int fk_DoctorId { get; set; }

    public int fk_Quarter { get; set; }

    public string fk_MonthNames { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public bool bitIsRequest { get; set; }

    public bool bitIsComplete { get; set; }

    public bool bitIsPending { get; set; }

    public bool bitIsCancel { get; set; }

    public int intYear { get; set; }

    public System.DateTime dtRequest { get; set; }

    public string vchRequestedBy { get; set; }

    public Nullable<System.DateTime> dtComplete { get; set; }

    public string vchCompletedBy { get; set; }

    public int intcode { get; set; }

    public bool bitTempComplete { get; set; }

    public string vchRefNumber { get; set; }

    public string vchBranchName { get; set; }

    public bool bitIsQuraterRequest { get; set; }

    public bool bitIsMonthRequest { get; set; }

    public Nullable<int> intFromMonth { get; set; }

    public Nullable<int> intToMonth { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsultantSlipDetail> tblConsultantSlipDetail { get; set; }

    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

    public virtual tblQuraterMas tblQuraterMas { get; set; }

}

}
