
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblConversation
{

    public int intid { get; set; }

    public int fk_intEmpid { get; set; }

    public int fk_uid { get; set; }

    public string fk_UserName { get; set; }

    public string vchMsg { get; set; }

    public System.DateTime dtMsgDate { get; set; }

    public string vchIpused { get; set; }

    public string vchHost { get; set; }

    public bool bitIsAuthorCancelReason { get; set; }

    public int intcode { get; set; }

    public bool bitIsAutorizationMsg { get; set; }



    public virtual tblUserMaster tblUserMaster { get; set; }

}

}
