
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblCurrentExpDetail
{

    public int intid { get; set; }

    public int fk_MasId { get; set; }

    public int fk_deptId { get; set; }

    public int fk_desiId { get; set; }

    public string vchstate { get; set; }

    public string vchCity { get; set; }

    public string vchAddress { get; set; }

    public string vchRefNo { get; set; }

    public string vchBranch { get; set; }

    public int intCode { get; set; }

    public string vchCreatedBy { get; set; }

    public System.DateTime DtCeated { get; set; }

    public string vchCreatedHost { get; set; }

    public string vchCratedIp { get; set; }

    public string vchUpdatedBy { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedHost { get; set; }

    public string vchUpdatedIP { get; set; }

    public string vchGender { get; set; }

    public string vchEmpFcode { get; set; }

    public string vchName { get; set; }

    public string vchFatherName { get; set; }

    public Nullable<System.DateTime> dtdoj { get; set; }

    public Nullable<int> fk_CityId { get; set; }

    public Nullable<int> fkStateId { get; set; }

    public bool bitIsDetailAvilable { get; set; }

    public bool bitIsDetailUpdated { get; set; }

    public bool bitEmpDetailUpdated { get; set; }



    public virtual tblDeptMas tblDeptMas { get; set; }

    public virtual tblDesignationMas tblDesignationMas { get; set; }

    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
