
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblConsultantSlipDetail
{

    public int intid { get; set; }

    public string vchMonth { get; set; }

    public System.Guid fk_SlipId { get; set; }

    public int intYear { get; set; }

    public Nullable<decimal> decAmount { get; set; }

    public Nullable<decimal> decTDS { get; set; }

    public Nullable<decimal> decNetAmount { get; set; }

    public string vchCreatedBy { get; set; }

    public Nullable<System.DateTime> dtCreated { get; set; }



    public virtual tblConsultantSlips tblConsultantSlips { get; set; }

}

}
