
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblCity
{

    public int intid { get; set; }

    public int fk_stateid { get; set; }

    public string vchCityName { get; set; }

    public string vchCreatedBy { get; set; }

    public Nullable<System.DateTime> dtCreated { get; set; }



    public virtual tblState tblState { get; set; }

}

}
