
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblConsultantDocDetail
{

    public int intid { get; set; }

    public int fk_DoctorID { get; set; }

    public int fk_DocMasId { get; set; }

    public string vchDocName { get; set; }

    public string vchDocAddress { get; set; }

    public string vchFileName { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCretaedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public string dtUpdated { get; set; }

    public string vchUp_By { get; set; }

    public string vchUp_IP { get; set; }

    public string vchUp_Host { get; set; }

    public bool bitIsUpload { get; set; }

    public bool bitIsLocked { get; set; }

    public bool bitIsProfile { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
