
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblDoctorUploadDetail
{

    public int intid { get; set; }

    public int fk_ConsultMasId { get; set; }

    public bool bitMOUUploaded { get; set; }

    public bool bitRegiUploaded { get; set; }

    public bool bitICompletedUpload { get; set; }

    public bool Option1 { get; set; }

    public bool Option2 { get; set; }

    public bool Option3 { get; set; }

    public bool bitMOUlocked { get; set; }

    public bool bitRegistrationlocked { get; set; }

    public bool bitOtherUploadLock { get; set; }

    public bool bitisVisiting { get; set; }

    public bool bitIsRegular { get; set; }

    public bool bitIsActive { get; set; }

    public bool bitIsLeft { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
