
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblDocDetails
{

    public int intid { get; set; }

    public int fk_empAssid { get; set; }

    public Nullable<int> fk_intdocid { get; set; }

    public Nullable<int> fk_qualiid { get; set; }

    public string vchdocname { get; set; }

    public string vchdocadd { get; set; }

    public string vchfilename { get; set; }

    public string vchcreatedby { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public Nullable<int> fk_NewAssEmpID { get; set; }

    public bool BitIsCompDoc { get; set; }

    public bool BitIsCompQuali { get; set; }

    public bool BitIsProfilePic { get; set; }



    public virtual tblDocMas tblDocMas { get; set; }

    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
