
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblDeptMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblDeptMas()
    {

        this.tblCurrentExpDetail = new HashSet<tblCurrentExpDetail>();

        this.tblDesignationMas = new HashSet<tblDesignationMas>();

        this.tblEmpAssesmentMas = new HashSet<tblEmpAssesmentMas>();

        this.tblEmpMas = new HashSet<tblEmpMas>();

        this.tblExperienceDetail = new HashSet<tblExperienceDetail>();

        this.tblIntershipDetail = new HashSet<tblIntershipDetail>();

        this.tblLetterAppointDetail = new HashSet<tblLetterAppointDetail>();

        this.tblLetterOfferDetail = new HashSet<tblLetterOfferDetail>();

        this.tblManPowerDetail = new HashSet<tblManPowerDetail>();

        this.tblTransferDetail = new HashSet<tblTransferDetail>();

        this.tblUserMaster = new HashSet<tblUserMaster>();

    }


    public int intid { get; set; }

    public string vchdeptname { get; set; }

    public string vchcreatedby { get; set; }

    public System.DateTime dtcreated { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public string vchupdatedipused { get; set; }

    public string vchupdatedhostname { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public Nullable<bool> IsSelected { get; set; }

    public string vchdepCode { get; set; }

    public bool bitIsByPassDept { get; set; }

    public Nullable<int> intManPower { get; set; }

    public bool bitIsCounterApplied { get; set; }

    public bool bitIsActive { get; set; }

    public bool bitIsInActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCurrentExpDetail> tblCurrentExpDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDesignationMas> tblDesignationMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpAssesmentMas> tblEmpAssesmentMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpMas> tblEmpMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblExperienceDetail> tblExperienceDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblIntershipDetail> tblIntershipDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLetterAppointDetail> tblLetterAppointDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLetterOfferDetail> tblLetterOfferDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblManPowerDetail> tblManPowerDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTransferDetail> tblTransferDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblUserMaster> tblUserMaster { get; set; }

}

}
