
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblDnbFeeStructure
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TblDnbFeeStructure()
    {

        this.TblDnbFeeSubmission = new HashSet<TblDnbFeeSubmission>();

    }


    public int FeeStructureId { get; set; }

    public int DnbStudentId { get; set; }

    public int YearNumber { get; set; }

    public string PayableTo { get; set; }

    public decimal Amount { get; set; }

    public System.DateTime DueDate { get; set; }

    public string PaymentStatus { get; set; }

    public string ApprovedBy { get; set; }

    public Nullable<System.DateTime> ApprovedDate { get; set; }

    public string Remarks { get; set; }



    public virtual TblDnbStudent TblDnbStudent { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblDnbFeeSubmission> TblDnbFeeSubmission { get; set; }

}

}
