
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblDoctorDocMas
{

    public int intid { get; set; }

    public string vchDocMasName { get; set; }

    public bool bitIsComplulsory { get; set; }

    public bool bitOtherOption { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIP { get; set; }

    public string vchUpdatedHost { get; set; }

    public bool bitIsSelected { get; set; }

    public string vchCompareFileAdd { get; set; }

    public Nullable<System.DateTime> dtTempUploaded { get; set; }

    public Nullable<int> TempEmpID { get; set; }

    public string vchTempFileName { get; set; }

}

}
