
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblDocTypeMas
{

    public int intTypeId { get; set; }

    public string vchDocTypeName { get; set; }

    public string dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchIpUsed { get; set; }

    public string vchHostName { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIp { get; set; }

    public string vchUpdatedHost { get; set; }

    public bool BitActive { get; set; }

}

}
