
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblDnbStudent
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TblDnbStudent()
    {

        this.TblDnbFeeStructure = new HashSet<TblDnbFeeStructure>();

    }


    public int DnbStudentId { get; set; }

    public int fk_EmployeeId { get; set; }

    public string CourseName { get; set; }

    public int DurationInYears { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public string Status { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public int intcode { get; set; }

    public Nullable<int> intyear { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblDnbFeeStructure> TblDnbFeeStructure { get; set; }

    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
