
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblDnbFeeSubmission
{

    public int SubmissionId { get; set; }

    public int FeeStructureId { get; set; }

    public string PaymentReferenceNo { get; set; }

    public string PaymentMode { get; set; }

    public System.DateTime PaymentDate { get; set; }

    public string PaymentScreenshotPath { get; set; }

    public string SubmittedBy { get; set; }

    public Nullable<System.DateTime> SubmittedDate { get; set; }

    public string VerifiedBy { get; set; }

    public Nullable<System.DateTime> VerificationDate { get; set; }

    public string VerifiedRemarks { get; set; }

    public string Status { get; set; }

    public string SubmissionRemarks { get; set; }

    public string FileName { get; set; }



    public virtual TblDnbFeeStructure TblDnbFeeStructure { get; set; }

}

}
