
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblDocMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblDocMas()
    {

        this.tblDocDetails = new HashSet<tblDocDetails>();

        this.tblPosDocMap = new HashSet<tblPosDocMap>();

    }


    public int intid { get; set; }

    public string vchdocname { get; set; }

    public string vchcreatedby { get; set; }

    public System.DateTime dtcreated { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public bool BitIsSelected { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDocDetails> tblDocDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPosDocMap> tblPosDocMap { get; set; }

}

}
