
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblEmpAssesmentDetails
{

    public int intid { get; set; }

    public int fk_positionid { get; set; }

    public int fk_AssEmpId { get; set; }

    public int fk_userid { get; set; }

    public string vchAssignedToUser { get; set; }

    public string vchCurrentStatus { get; set; }

    public bool BitIsAssignCompleted { get; set; }

    public bool BitIsSelected { get; set; }

    public string vchCompletedBy { get; set; }

    public Nullable<System.DateTime> dtCompleted { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public int intcode { get; set; }

    public int intyr { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

    public virtual tblPositionCategoryMas tblPositionCategoryMas { get; set; }

    public virtual tblUserMaster tblUserMaster { get; set; }

}

}
