
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblExperienceMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblExperienceMas()
    {

        this.tblExperienceDetail = new HashSet<tblExperienceDetail>();

    }


    public int intid { get; set; }

    public string vchName { get; set; }

    public string vchType { get; set; }

    public string vchForGender { get; set; }

    public string vchHeading { get; set; }

    public string txtContent { get; set; }

    public string vchLetterCode { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIp { get; set; }

    public string vchUpdatedHost { get; set; }

    public int intcode { get; set; }

    public Nullable<int> intyear { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblExperienceDetail> tblExperienceDetail { get; set; }

}

}
