
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblEmpDetails
{

    public int intid { get; set; }

    public int fk_intempid { get; set; }

    public string vchsex { get; set; }

    public string vchmaritalststus { get; set; }

    public Nullable<System.DateTime> dtDob { get; set; }

    public Nullable<int> intage { get; set; }

    public string vchFatherName { get; set; }

    public string vchmothername { get; set; }

    public string vchspouse { get; set; }

    public string vchtaddress { get; set; }

    public string vchtstate { get; set; }

    public string vchtcity { get; set; }

    public Nullable<int> inttpin { get; set; }

    public string vchtmobile { get; set; }

    public string vchpaddress { get; set; }

    public string vchpstate { get; set; }

    public string vchpcity { get; set; }

    public string vchpstreet { get; set; }

    public Nullable<int> intppin { get; set; }

    public string vchpmobile { get; set; }

    public string vchcreatedby { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public Nullable<bool> BitIsSelected { get; set; }

    public Nullable<bool> BitCompleted { get; set; }

    public string vchNominee { get; set; }

    public string vchRelation { get; set; }

    public Nullable<int> fk_titid { get; set; }

    public string vchEmpTcode { get; set; }

    public string vchEmpFcode { get; set; }

    public string vchfname { get; set; }

    public string vchmname { get; set; }

    public string vchlname { get; set; }

    public string vchupdatedip { get; set; }

    public string vchupdatedhost { get; set; }

    public Nullable<int> fk_State { get; set; }

    public Nullable<int> fk_city { get; set; }

    public string vchQualifications { get; set; }

    public Nullable<int> fk_tCity { get; set; }

    public Nullable<int> fktState { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

    public virtual tblTitleMas tblTitleMas { get; set; }

}

}
