
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblEmpLoginUser
{

    public int intid { get; set; }

    public int fk_intEmpID { get; set; }

    public string vchmobile { get; set; }

    public string vchOTP { get; set; }

    public Nullable<System.DateTime> dtlastlogin { get; set; }

    public Nullable<bool> BitUploadStatus { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchcreatedby { get; set; }

    public int intcode { get; set; }

    public int intyr { get; set; }

    public bool bitProfileComplete { get; set; }

    public bool bitSigUploaded { get; set; }

    public string vchProfileName { get; set; }

    public string vchProfilePath { get; set; }

    public string vchSigName { get; set; }

    public string vchSigPath { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public bool bitISAllowedFirstDayLeave { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
