
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblEmpExitMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblEmpExitMas()
    {

        this.tblEMpExitDetail = new HashSet<tblEMpExitDetail>();

    }


    public int intid { get; set; }

    public int fkEmpid { get; set; }

    public string vchExitType { get; set; }

    public string vchReasonExit { get; set; }

    public string vchReason2Exit { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBY { get; set; }

    public string vchCretaedHost { get; set; }

    public string vchCreatedIp { get; set; }

    public Nullable<System.DateTime> dtApproved { get; set; }

    public string vchApprovedBy { get; set; }

    public string vchApporvedHost { get; set; }

    public string vchApprovedIP { get; set; }

    public bool bitIsCompleted { get; set; }

    public bool bitIsApproved { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEMpExitDetail> tblEMpExitDetail { get; set; }

}

}
