
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblEmpAssesmentMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblEmpAssesmentMas()
    {

        this.tblConsultantDocDetail = new HashSet<tblConsultantDocDetail>();

        this.tblConsultantLedgerDetail = new HashSet<tblConsultantLedgerDetail>();

        this.tblCurrentExpDetail = new HashSet<tblCurrentExpDetail>();

        this.tblDocDetails = new HashSet<tblDocDetails>();

        this.tblDoctorUploadDetail = new HashSet<tblDoctorUploadDetail>();

        this.tblEmpAssesmentDetails = new HashSet<tblEmpAssesmentDetails>();

        this.tblEmpDetails = new HashSet<tblEmpDetails>();

        this.tblEmpExitMas = new HashSet<tblEmpExitMas>();

        this.tblEmpLoginUser = new HashSet<tblEmpLoginUser>();

        this.tblKRADocDetail = new HashSet<tblKRADocDetail>();

        this.tblLetterAppointDetail = new HashSet<tblLetterAppointDetail>();

        this.tblMouDetail = new HashSet<tblMouDetail>();

        this.tblRegistrationDetail = new HashSet<tblRegistrationDetail>();

        this.tblSalaryIncrement = new HashSet<tblSalaryIncrement>();

        this.tblTransferDetail = new HashSet<tblTransferDetail>();

        this.tblVPForward = new HashSet<tblVPForward>();

        this.tblConsultantSlips = new HashSet<tblConsultantSlips>();

        this.tblLeaveApplication = new HashSet<tblLeaveApplication>();

        this.tblConsultantTDS = new HashSet<tblConsultantTDS>();

        this.TblDnbStudent = new HashSet<TblDnbStudent>();

    }


    public int intid { get; set; }

    public string vchName { get; set; }

    public string vchMobile { get; set; }

    public int fk_PositionId { get; set; }

    public Nullable<decimal> decExperience { get; set; }

    public string vchWorkedArea { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchcreatedby { get; set; }

    public string vchcreatedhost { get; set; }

    public string vchcreatedipused { get; set; }

    public string vchAssignedBy { get; set; }

    public Nullable<System.DateTime> dtAssign { get; set; }

    public string vchAssignhostname { get; set; }

    public string vchAssignipused { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public string vchupdatedhostname { get; set; }

    public string vchupdatedipused { get; set; }

    public bool BitIsselected { get; set; }

    public bool BitCompleteAssesment { get; set; }

    public bool BitAssesmentResultPass { get; set; }

    public string vch_Status { get; set; }

    public bool BitStatus { get; set; }

    public bool BitAllowUpload { get; set; }

    public bool BitIsUploadCompleted { get; set; }

    public Nullable<decimal> decSkillMarks { get; set; }

    public string vchSkillStatus { get; set; }

    public bool BitAssesmentResultFail { get; set; }

    public string After { get; set; }

    public Nullable<int> fk_inttitid { get; set; }

    public string vchempcode { get; set; }

    public string vchfname { get; set; }

    public string vchmname { get; set; }

    public string vchlname { get; set; }

    public Nullable<int> fk_intdeptid { get; set; }

    public Nullable<int> fk_intdesiid { get; set; }

    public string vchEmpTcode { get; set; }

    public string vchEmpFcode { get; set; }

    public Nullable<System.DateTime> dtDOJ { get; set; }

    public Nullable<int> intsalary { get; set; }

    public Nullable<System.DateTime> dtDOL { get; set; }

    public bool bittempstatusactive { get; set; }

    public bool bittofficialdetails { get; set; }

    public bool bitofficialdetails { get; set; }

    public bool bittempqualidetails { get; set; }

    public bool bittempperdetails { get; set; }

    public bool bittempcontdetails { get; set; }

    public bool bitstatusdeactive { get; set; }

    public bool bitqualidetails { get; set; }

    public bool bitperdetails { get; set; }

    public bool bitcontdetails { get; set; }

    public bool bitgoauthor { get; set; }

    public bool bitauthorised { get; set; }

    public Nullable<System.DateTime> dtupdatedby { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public string vchhostname { get; set; }

    public string ipdaddressused { get; set; }

    public string vchauthorisedby { get; set; }

    public Nullable<System.DateTime> dtauthorised { get; set; }

    public string vchipdusedauthor { get; set; }

    public string vchautorisedhost { get; set; }

    public string vchdeactiveby { get; set; }

    public Nullable<System.DateTime> dtdecavited { get; set; }

    public string vchdeactivedipused { get; set; }

    public string vchdeactivedhost { get; set; }

    public bool bitauthorcancel { get; set; }

    public string vchcancelreason { get; set; }

    public string vchauthorisedmsg { get; set; }

    public string vchFinalUpdatedBy { get; set; }

    public Nullable<System.DateTime> dtFinalUpdated { get; set; }

    public string vchFinalHostname { get; set; }

    public string vchFinalipused { get; set; }

    public bool bitCompDocT { get; set; }

    public bool bitCompDocP { get; set; }

    public bool bitProfileComplete { get; set; }

    public bool bitIsReplacement { get; set; }

    public string vchRplcmntName { get; set; }

    public string vchAssDeactiveRemarks { get; set; }

    public string vchAssDeactiveBy { get; set; }

    public Nullable<System.DateTime> vchAssDeactiveDt { get; set; }

    public bool bitAuthorBack { get; set; }

    public string vchHrSolRemark { get; set; }

    public bool bitIsUnjoined { get; set; }

    public Nullable<System.DateTime> dtFDOJ { get; set; }

    public string vchUnjoinBy { get; set; }

    public Nullable<System.DateTime> dtUnjoined { get; set; }

    public string vchArea { get; set; }

    public Nullable<bool> bitIsCorporateemp { get; set; }

    public Nullable<bool> bitIsUnitEmp { get; set; }

    public string vchEmpOldCode { get; set; }

    public Nullable<bool> isHrmsEmployee { get; set; }

    public Nullable<bool> isPayrollEmployee { get; set; }

    public string vchgender { get; set; }

    public bool bitIsByPassEntry { get; set; }

    public bool bitIsPartialAuthorised { get; set; }

    public bool BitIsFlaggingEmp { get; set; }

    public bool BitIsRedFlagging { get; set; }

    public bool BitIsOrangeFlagging { get; set; }

    public bool BitIsGreenFlagging { get; set; }

    public string vchAadharNo { get; set; }

    public string vchFlagRemarks { get; set; }

    public bool bitOfferLetter { get; set; }

    public bool bitExpLetter { get; set; }

    public bool bitJoinLetter { get; set; }

    public bool bitOfferLGiven { get; set; }

    public bool bitExpLGiven { get; set; }

    public bool bitJoinLGiven { get; set; }

    public bool bitInterShipLetter { get; set; }

    public bool bitInterShipGiven { get; set; }

    public string vchUpdatePartialToActive { get; set; }

    public Nullable<System.DateTime> dtPartialUpdate { get; set; }

    public bool bitIsTransferred { get; set; }

    public bool bitIsRecieved { get; set; }

    public bool bitIsFinalPoliceVeriDone { get; set; }

    public bool bitIsTerminated { get; set; }

    public bool bitIsLeft { get; set; }

    public string vchTransferRemarks { get; set; }

    public string vchReceiveRemarks { get; set; }

    public bool bitIsConsultant { get; set; }

    public string PAN_NO { get; set; }

    public bool bitIsCurrentExp { get; set; }

    public Nullable<int> intVariable { get; set; }

    public Nullable<int> intFixed { get; set; }

    public Nullable<int> intTotal { get; set; }

    public bool bitIsKRAEligible { get; set; }

    public Nullable<System.DateTime> dtFirstAuthor { get; set; }

    public Nullable<System.DateTime> dtApprovedAuthor { get; set; }

    public Nullable<System.DateTime> dtCreateGetDate { get; set; }

    public bool bitAllowExit { get; set; }

    public bool bitAssignExitForm { get; set; }

    public bool bitExitFormApproved { get; set; }

    public bool bitNotCountInManPower { get; set; }

    public bool bitIsFwardVp { get; set; }

    public bool bitIsAprvdVp { get; set; }

    public string vchPANNUmber { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsultantDocDetail> tblConsultantDocDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsultantLedgerDetail> tblConsultantLedgerDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCurrentExpDetail> tblCurrentExpDetail { get; set; }

    public virtual tblDeptMas tblDeptMas { get; set; }

    public virtual tblDesignationMas tblDesignationMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDocDetails> tblDocDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDoctorUploadDetail> tblDoctorUploadDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpAssesmentDetails> tblEmpAssesmentDetails { get; set; }

    public virtual tblEmpAssesmentMas tblEmpAssesmentMas1 { get; set; }

    public virtual tblEmpAssesmentMas tblEmpAssesmentMas2 { get; set; }

    public virtual tblPositionCategoryMas tblPositionCategoryMas { get; set; }

    public virtual tblTitleMas tblTitleMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpDetails> tblEmpDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpExitMas> tblEmpExitMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpLoginUser> tblEmpLoginUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblKRADocDetail> tblKRADocDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLetterAppointDetail> tblLetterAppointDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMouDetail> tblMouDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRegistrationDetail> tblRegistrationDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblSalaryIncrement> tblSalaryIncrement { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTransferDetail> tblTransferDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblVPForward> tblVPForward { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsultantSlips> tblConsultantSlips { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLeaveApplication> tblLeaveApplication { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsultantTDS> tblConsultantTDS { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblDnbStudent> TblDnbStudent { get; set; }

}

}
