
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblEmpMas
{

    public int intempid { get; set; }

    public int inttitid { get; set; }

    public string vchname { get; set; }

    public string vchempcode { get; set; }

    public string vchEmpTcode { get; set; }

    public string vchEmpFcode { get; set; }

    public string vchfname { get; set; }

    public string vchmname { get; set; }

    public string vchlname { get; set; }

    public int intdeptid { get; set; }

    public string vchdeptname { get; set; }

    public int intdesiid { get; set; }

    public string vchdesignation { get; set; }

    public Nullable<System.DateTime> dtDOJ { get; set; }

    public Nullable<int> intsalary { get; set; }

    public Nullable<System.DateTime> dtDOL { get; set; }

    public bool bittempstatusactive { get; set; }

    public bool bittofficialdetails { get; set; }

    public bool bitofficialdetails { get; set; }

    public bool bittempqualidetails { get; set; }

    public bool bittempperdetails { get; set; }

    public bool bittempcontdetails { get; set; }

    public bool bitstatusdeactive { get; set; }

    public bool bitqualidetails { get; set; }

    public bool bitperdetails { get; set; }

    public bool bitcontdetails { get; set; }

    public bool bitgoauthor { get; set; }

    public bool bitauthorised { get; set; }

    public string vchcreatedby { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdatedby { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public string vchhostname { get; set; }

    public string ipdaddressused { get; set; }

    public bool BitIsSelected { get; set; }

    public string vchauthorisedby { get; set; }

    public Nullable<System.DateTime> dtauthorised { get; set; }

    public string vchipdusedauthor { get; set; }

    public string vchautorisedhost { get; set; }

    public string vchdeactiveby { get; set; }

    public Nullable<System.DateTime> dtdecavited { get; set; }

    public string vchdeactivedipused { get; set; }

    public string vchdeactivedhost { get; set; }

    public bool bitauthorcancel { get; set; }

    public string vchcancelreason { get; set; }

    public string vchauthorisedmsg { get; set; }

    public string vchFinalUpdatedBy { get; set; }

    public Nullable<System.DateTime> dtFinalUpdated { get; set; }

    public string vchFinalHostname { get; set; }

    public string vchFinalipused { get; set; }



    public virtual tblDeptMas tblDeptMas { get; set; }

    public virtual tblDesignationMas tblDesignationMas { get; set; }

    public virtual tblTitleMas tblTitleMas { get; set; }

}

}
