
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblEMpExitDetail
{

    public int intid { get; set; }

    public int fk_ExitMasid { get; set; }

    public int fk_Qid { get; set; }

    public string vchAnswer { get; set; }

    public System.DateTime dtCretated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCreatedHost { get; set; }

    public string vchCreatedIP { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedHost { get; set; }

    public string vchUpdatedIP { get; set; }



    public virtual tblEmpExitMas tblEmpExitMas { get; set; }

    public virtual tblExitInterviewQuestMas tblExitInterviewQuestMas { get; set; }

}

}
