
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblExitInterviewQuestMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblExitInterviewQuestMas()
    {

        this.tblEMpExitDetail = new HashSet<tblEMpExitDetail>();

    }


    public int intid { get; set; }

    public string vchQuestion { get; set; }

    public Nullable<System.DateTime> dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCretaedHost { get; set; }

    public string vchCreatedIp { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEMpExitDetail> tblEMpExitDetail { get; set; }

}

}
