
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblIntershipMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblIntershipMas()
    {

        this.tblIntershipDetail = new HashSet<tblIntershipDetail>();

    }


    public int intid { get; set; }

    public string vchMasName { get; set; }

    public string txtMasContent { get; set; }

    public string vchLetterCode { get; set; }

    public string vchLetterHeading { get; set; }

    public string vchForGender { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIp { get; set; }

    public string vchUpdatedHost { get; set; }

    public int intcode { get; set; }

    public int intyear { get; set; }

    public System.DateTime dtServerCreation { get; set; }

    public string vchType { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblIntershipDetail> tblIntershipDetail { get; set; }

}

}
