
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblIntershipDetail
{

    public int intid { get; set; }

    public int fk_Masid { get; set; }

    public string vchName { get; set; }

    public string vchFatherName { get; set; }

    public System.DateTime dtApplication { get; set; }

    public System.DateTime dtDOS { get; set; }

    public System.DateTime dtDOE { get; set; }

    public string txtContent { get; set; }

    public string vchCompany { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIp { get; set; }

    public string vchUpdatedHost { get; set; }

    public int intcode { get; set; }

    public int intyear { get; set; }

    public System.DateTime dtServerCreation { get; set; }

    public bool bitIsHRMSemp { get; set; }

    public bool bitIsEditLock { get; set; }

    public Nullable<int> fk_hrmsEMPid { get; set; }

    public string vchState { get; set; }

    public string vchCity { get; set; }

    public string vchAddress { get; set; }

    public string vchEmpCode { get; set; }

    public int fk_department { get; set; }

    public int fk_designation { get; set; }

    public string vchRef_No { get; set; }

    public string vchGender { get; set; }



    public virtual tblDeptMas tblDeptMas { get; set; }

    public virtual tblDesignationMas tblDesignationMas { get; set; }

    public virtual tblIntershipMas tblIntershipMas { get; set; }

}

}
