
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblJoiningRemarks
{

    public int intid { get; set; }

    public int fk_EmpId { get; set; }

    public string vchremarks { get; set; }

    public string vchRemarksBy { get; set; }

    public System.DateTime dtRemarks { get; set; }

    public string vchHostName { get; set; }

    public string vchIpUsed { get; set; }

    public bool bitIsEDOJ { get; set; }

    public bool bitIsFDOJ { get; set; }

    public int fk_useridUsed { get; set; }



    public virtual tblUserMaster tblUserMaster { get; set; }

}

}
