
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblKRADocDetail
{

    public int intID { get; set; }

    public int fk_EmpID { get; set; }

    public string vchFileName { get; set; }

    public string vchFileAddress { get; set; }

    public System.DateTime dtUpload { get; set; }

    public string vchUpBy { get; set; }

    public int itncode { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpDatedBy { get; set; }

    public string vchDocMasName { get; set; }

    public decimal decFinalScore { get; set; }

    public decimal decMaxScore { get; set; }

    public Nullable<decimal> decCohortScore { get; set; }

    public int fk_intDeptid { get; set; }

    public Nullable<decimal> intTempCohort { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
