
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblLetterNumberMas
{

    public int intid { get; set; }

    public int intStart { get; set; }

    public int intCurrent { get; set; }

    public int intcode { get; set; }

    public int intYear { get; set; }

}

}
