
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblLeaveType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblLeaveType()
    {

        this.tblLeaveApplication = new HashSet<tblLeaveApplication>();

    }


    public System.Guid unID { get; set; }

    public string leaveType { get; set; }

    public string vchCreatedBy { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIP { get; set; }

    public string vchUpdatedHost { get; set; }

    public Nullable<decimal> decMaxDayPerYear { get; set; }

    public Nullable<bool> bitIsUseInEmgLeave { get; set; }

    public Nullable<decimal> decMinOnce { get; set; }

    public Nullable<decimal> decMaxOnce { get; set; }

    public Nullable<bool> bitForEmployee { get; set; }

    public bool bitForConsultant { get; set; }

    public bool bitAllowYearHalfCheck { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLeaveApplication> tblLeaveApplication { get; set; }

}

}
