
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblLeaveBalance
{

    public System.Guid unID { get; set; }

    public int fk_Empid { get; set; }

    public System.Guid fk_LeaveType { get; set; }

    public System.DateTime year { get; set; }

    public int intLeaveBalance { get; set; }

    public string vchCreatedBy { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIP { get; set; }

    public string vchUpdatedHost { get; set; }

    public Nullable<System.Guid> fk_YearID { get; set; }

}

}
