
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblLetterAppointMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblLetterAppointMas()
    {

        this.tblLetterAppointDetail = new HashSet<tblLetterAppointDetail>();

    }


    public int intid { get; set; }

    public string vchMasType { get; set; }

    public string vchMasName { get; set; }

    public string TextMasContent { get; set; }

    public string vchMasLetterCode { get; set; }

    public string vchMasHeading { get; set; }

    public string vchForGender { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIp { get; set; }

    public string vchUpdatedHost { get; set; }

    public int intcode { get; set; }

    public int intyear { get; set; }

    public System.DateTime dtServerCreation { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLetterAppointDetail> tblLetterAppointDetail { get; set; }

}

}
