
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblLeaveApplication
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblLeaveApplication()
    {

        this.tblLeaveApplicationDetail = new HashSet<tblLeaveApplicationDetail>();

    }


    public System.Guid unID { get; set; }

    public int fk_Empid { get; set; }

    public System.Guid fk_LeaveType { get; set; }

    public System.DateTime dtStartFrom { get; set; }

    public System.DateTime dtEndDate { get; set; }

    public string vchReason { get; set; }

    public string vchStatus { get; set; }

    public string vchCreatedBy { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIP { get; set; }

    public string vchUpdatedHost { get; set; }

    public string vchApprovedBy { get; set; }

    public Nullable<System.DateTime> dtApproved { get; set; }

    public string leaveDateRange { get; set; }

    public decimal decdaysRequest { get; set; }

    public Nullable<decimal> decdaysApproved { get; set; }

    public string appovedDateRange { get; set; }

    public bool bitSameApprove { get; set; }

    public bool bitLessApprove { get; set; }

    public int intCode { get; set; }

    public bool bitIsApproved { get; set; }

    public bool bitIsRejected { get; set; }

    public bool bitIsPartialApproved { get; set; }

    public bool TempBitAssignedHOD { get; set; }

    public bool TempBitHODComplete { get; set; }

    public bool TempBitAssignedHR { get; set; }

    public bool TempBitHRComplete { get; set; }

    public bool TempbitHODNotFound { get; set; }

    public bool bitISHalfDay { get; set; }

    public bool bitISVpAssigned { get; set; }

    public bool bitISVpApproved { get; set; }

    public string vchApprovalType { get; set; }

    public Nullable<System.Guid> fk_YearID { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLeaveApplicationDetail> tblLeaveApplicationDetail { get; set; }

    public virtual tblLeaveType tblLeaveType { get; set; }

}

}
