
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblLeaveApplicationDetail
{

    public System.Guid UN_ID { get; set; }

    public System.Guid fk_AppID { get; set; }

    public string vchAssignedUser { get; set; }

    public int fk_AssignUserid { get; set; }

    public System.DateTime dtAssigned { get; set; }

    public string vchCurrentStatus { get; set; }

    public bool bitIsSameApproved { get; set; }

    public bool BitIsPartialApproved { get; set; }

    public bool BitIsRejected { get; set; }

    public Nullable<System.DateTime> dtApproved { get; set; }

    public string vchApprovedBy { get; set; }

    public string vchApprovedHost { get; set; }

    public string vchApprovedIP { get; set; }

    public Nullable<int> intCode { get; set; }

    public string vchGetApprovalType { get; set; }

    public string vchApproveRemarks { get; set; }

    public bool bitAssignedHOD { get; set; }

    public bool bitHODComplete { get; set; }

    public bool bitAssignedHR { get; set; }

    public bool bitHRComplete { get; set; }

    public bool bitHODNotFound { get; set; }

    public string dtApprovedRange { get; set; }

    public Nullable<decimal> decApprvedDays { get; set; }

    public Nullable<bool> bitISApproved { get; set; }

    public Nullable<bool> bitISAssigned { get; set; }

    public Nullable<bool> bitHalfDay { get; set; }

    public bool bitISVpAssigned { get; set; }

    public bool bitISVpApproved { get; set; }



    public virtual tblLeaveApplication tblLeaveApplication { get; set; }

}

}
