
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblMouDetail
{

    public int intid { get; set; }

    public int fk_EMpid { get; set; }

    public System.DateTime dtMOUCreated { get; set; }

    public System.DateTime dtEffectFrom { get; set; }

    public System.DateTime dtEffectTo { get; set; }

    public bool bitIsOLD { get; set; }

    public bool bitIsCurrent { get; set; }

    public bool bitIsRenew { get; set; }

    public Nullable<System.DateTime> dtCretaed { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCretaedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIP { get; set; }

    public string vchFileName { get; set; }

    public string vchFileAddress { get; set; }

    public string vchDocName { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
