
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblManPowerDetail
{

    public int intid { get; set; }

    public int fk_deptid { get; set; }

    public int fk_masID { get; set; }

    public int intManPowerCount { get; set; }

    public bool bitAllowManpowerCheck { get; set; }

    public int intCode { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchCreatedHost { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIP { get; set; }

    public string vchUpdatedost { get; set; }



    public virtual tblDeptMas tblDeptMas { get; set; }

    public virtual tblManPowerMas tblManPowerMas { get; set; }

}

}
