
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblMonthMaster
{

    public int intid { get; set; }

    public string Month { get; set; }

    public Nullable<System.DateTime> dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public bool bitIsUploaded { get; set; }

    public string vchTempDocAddress { get; set; }

    public string vchTempFileName { get; set; }

    public string vchTempDocMasName { get; set; }

    public Nullable<System.DateTime> dtTempUploaded { get; set; }

    public Nullable<int> intTempEmpID { get; set; }

    public Nullable<decimal> decTempScore { get; set; }

    public Nullable<decimal> decMaxScore { get; set; }

    public Nullable<decimal> decCohortScore { get; set; }

}

}
