
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblManPowerMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblManPowerMas()
    {

        this.tblManPowerDetail = new HashSet<tblManPowerDetail>();

    }


    public int intid { get; set; }

    public int fk_Branch { get; set; }

    public bool bitIsmapping { get; set; }

    public string vchCreatedBy { get; set; }

    public System.DateTime dtCreated { get; set; }

    public string vchCreatedHost { get; set; }

    public string vchCreatedIP { get; set; }

    public string vchUpdatedBy { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedHost { get; set; }

    public string vchUpdatedIP { get; set; }

    public string vchBranchName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblManPowerDetail> tblManPowerDetail { get; set; }

}

}
