
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblOtherDocumentMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblOtherDocumentMas()
    {

        this.tblOtherDocDetail = new HashSet<tblOtherDocDetail>();

    }


    public int intid { get; set; }

    public string vchDocName { get; set; }

    public bool bitISMultipleRecords { get; set; }

    public System.DateTime dtCretaed { get; set; }

    public string vchCretaedBy { get; set; }

    public string vchCretaedHost { get; set; }

    public string vchCretaedIP { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedHost { get; set; }

    public string vchUpdatedIP { get; set; }

    public int intcode { get; set; }

    public bool bitIsSelected { get; set; }

    public string vchCompareFileAdd { get; set; }

    public Nullable<System.DateTime> dtTempUploaded { get; set; }

    public Nullable<int> TempEmpID { get; set; }

    public string vchTempDocName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblOtherDocDetail> tblOtherDocDetail { get; set; }

}

}
