
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblPositionCategoryMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblPositionCategoryMas()
    {

        this.tblEmpAssesmentDetails = new HashSet<tblEmpAssesmentDetails>();

        this.tblEmpAssesmentMas = new HashSet<tblEmpAssesmentMas>();

        this.tblPosDesiMap = new HashSet<tblPosDesiMap>();

        this.tblPosDocMap = new HashSet<tblPosDocMap>();

        this.tblRequisition = new HashSet<tblRequisition>();

        this.tblSkillMarksAndPositionMappMas = new HashSet<tblSkillMarksAndPositionMappMas>();

    }


    public int intid { get; set; }

    public string vchPosCatName { get; set; }

    public string vchcreatedby { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public string vchupdatedipused { get; set; }

    public string vchupdatedhostname { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public Nullable<bool> IsSelected { get; set; }

    public bool BitDesiMapping { get; set; }

    public bool BitSkillMapping { get; set; }

    public bool BitDocMapping { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpAssesmentDetails> tblEmpAssesmentDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpAssesmentMas> tblEmpAssesmentMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPosDesiMap> tblPosDesiMap { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPosDocMap> tblPosDocMap { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRequisition> tblRequisition { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblSkillMarksAndPositionMappMas> tblSkillMarksAndPositionMappMas { get; set; }

}

}
