
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblPosDocMap
{

    public int intid { get; set; }

    public int fk_PosCatid { get; set; }

    public int fk_docid { get; set; }

    public string vchcreatedby { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public string vchupdatedipused { get; set; }

    public string vchupdatedhostname { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public bool IsSelected { get; set; }

    public bool BitIsUploaded { get; set; }

    public string ComparedFileName { get; set; }

    public Nullable<int> fk_TempEmpId { get; set; }

    public Nullable<int> fk_TempCompDocid { get; set; }

    public Nullable<System.DateTime> dt_TempUploaded { get; set; }

    public bool bitRequireForAuthorization { get; set; }

    public bool bitRequireForPartialToComplete { get; set; }



    public virtual tblDocMas tblDocMas { get; set; }

    public virtual tblPositionCategoryMas tblPositionCategoryMas { get; set; }

}

}
