
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblPayrollData
{

    public int intid { get; set; }

    public string Name { get; set; }

    public System.DateTime dtDOJ { get; set; }

    public string vchMobile { get; set; }

    public string vchEMpCode { get; set; }

    public string vchGender { get; set; }

    public string vchFatherName { get; set; }

    public string vchMotherName { get; set; }

    public string vchSpouseName { get; set; }

    public int intCode { get; set; }

    public bool BitInHRMS { get; set; }

    public string AadhaarNo { get; set; }

}

}
