
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblPermissionMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblPermissionMaster()
    {

        this.tblUserPermission = new HashSet<tblUserPermission>();

    }


    public int intid { get; set; }

    public string fk_GName { get; set; }

    public int fk_Gpid { get; set; }

    public string vchPermissionName { get; set; }

    public Nullable<System.DateTime> dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchipused { get; set; }

    public string vchHostname { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedipused { get; set; }

    public string vchupdatedHostname { get; set; }

    public bool bitIsselected { get; set; }

    public int intcode { get; set; }

    public int intyr { get; set; }



    public virtual tblGroupMaster tblGroupMaster { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblUserPermission> tblUserPermission { get; set; }

}

}
