
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblQuraterMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblQuraterMas()
    {

        this.tblConsultantSlips = new HashSet<tblConsultantSlips>();

        this.tblConsultantTDS = new HashSet<tblConsultantTDS>();

    }


    public int intid { get; set; }

    public string vchMonth { get; set; }

    public int intQurater { get; set; }

    public System.DateTime dtCreated { get; set; }

    public bool TempBitIsUploaded { get; set; }

    public string vchTempDocAddress { get; set; }

    public string vchTempFileName { get; set; }

    public string vchTempDocMasName { get; set; }

    public Nullable<System.DateTime> dtTempUploaded { get; set; }

    public Nullable<int> intTempEmpid { get; set; }

    public string vchTempYear { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsultantSlips> tblConsultantSlips { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsultantTDS> tblConsultantTDS { get; set; }

}

}
