
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblQualiDetails
{

    public int intid { get; set; }

    public int intempid { get; set; }

    public int fk_intqualiid { get; set; }

    public string vchqname { get; set; }

    public string vchcreatedby { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public Nullable<bool> bitissleceted { get; set; }



    public virtual tblQualiMas tblQualiMas { get; set; }

}

}
