
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblQualiMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblQualiMas()
    {

        this.tblQualiDetails = new HashSet<tblQualiDetails>();

    }


    public int intqualiid { get; set; }

    public string vchqname { get; set; }

    public string vchcreatedby { get; set; }

    public System.DateTime dtcreated { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public int intcode { get; set; }

    public int intyr { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public Nullable<bool> BitIsSlected { get; set; }

    public bool BitIsFinalDoc { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQualiDetails> tblQualiDetails { get; set; }

}

}
