
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblRequisition
{

    public int intid { get; set; }

    public int vchReqType { get; set; }

    public bool BitIsReplacement { get; set; }

    public string fkReplacement_empid { get; set; }

    public Nullable<int> fk_PositionID { get; set; }

    public string vchEducation { get; set; }

    public string vchAditionalEducation { get; set; }

    public string vchSkill { get; set; }

    public int intExpRequired { get; set; }

    public System.DateTime dtRequiredDate { get; set; }

    public System.DateTime dtRequest { get; set; }

    public string vchRequestBy { get; set; }

    public bool bitRequestByMgr { get; set; }

    public bool bitRequestByHR { get; set; }

    public bool bitRequestByVPHR { get; set; }

    public string vchRequestIP { get; set; }

    public string vchRequestHost { get; set; }

    public bool btiISAssignFromMgr { get; set; }

    public bool bitISAssignFromHR { get; set; }

    public bool bitISAssignFromVPHR { get; set; }

    public bool bitISAssignToHR { get; set; }

    public bool bitISAssignToVPHR { get; set; }

    public bool bitISAssignToCFO { get; set; }

    public bool bitISForwardFromHR { get; set; }

    public Nullable<System.DateTime> dtForwardFromHR { get; set; }

    public bool bitISForwardFromVPHR { get; set; }

    public Nullable<System.DateTime> dtForwardFromVPHR { get; set; }

    public bool bitISApprovedByHR { get; set; }

    public Nullable<System.DateTime> dtApprovedByHR { get; set; }

    public bool bitISApprvoedByVPHR { get; set; }

    public Nullable<System.DateTime> dtApprovedByVPHR { get; set; }

    public bool bitISApprovedByCFO { get; set; }

    public Nullable<System.DateTime> dtApprovedByCFO { get; set; }

    public bool bitStatusForward { get; set; }

    public bool bitStatusPending { get; set; }

    public bool bitStatusComplete { get; set; }

    public string vchTypeName { get; set; }

    public bool bitISNew { get; set; }

    public int intCode { get; set; }

    public string vchRemarks { get; set; }

    public string vchApprovalRemarks { get; set; }

    public bool bitStatusCancel { get; set; }

    public Nullable<System.DateTime> dtCancel { get; set; }

    public string vchCancelBy { get; set; }

    public bool bitCancelByHR { get; set; }

    public bool bitCancelByVPHR { get; set; }

    public bool bitCancelByCFO { get; set; }

    public Nullable<System.DateTime> dtApproved { get; set; }

    public string vchApprovedBy { get; set; }

    public string vchRNumber { get; set; }

    public string vchRplcMentName { get; set; }

    public string vchRplcMentEmpCode { get; set; }



    public virtual tblPositionCategoryMas tblPositionCategoryMas { get; set; }

}

}
