
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblRequisitionNumberMas
{

    public int intid { get; set; }

    public Nullable<int> intStart { get; set; }

    public Nullable<int> intCurrent { get; set; }

    public System.DateTime dtstart { get; set; }

}

}
