
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblSkillMarksAndPositionMappMas
{

    public int intid { get; set; }

    public int fk_PositionID { get; set; }

    public int intSkillMarksFm { get; set; }

    public int intSkillMarksTo { get; set; }

    public string vchCreatedBy { get; set; }

    public Nullable<System.DateTime> dtCreated { get; set; }

    public string vchIpUsed { get; set; }

    public string vchHostname { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedIpUsed { get; set; }

    public string vchUpdatedHost { get; set; }

    public Nullable<int> intCode { get; set; }

    public Nullable<int> intYear { get; set; }

    public bool BitMapped { get; set; }

    public bool BitIsSelected { get; set; }



    public virtual tblPositionCategoryMas tblPositionCategoryMas { get; set; }

}

}
