
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblState
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblState()
    {

        this.tblCity = new HashSet<tblCity>();

    }


    public int intid { get; set; }

    public string vchState { get; set; }

    public string vchcreatedBy { get; set; }

    public Nullable<System.DateTime> dtCreated { get; set; }

    public bool bitIsActive { get; set; }

    public bool bitIsUT { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCity> tblCity { get; set; }

}

}
