
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblSalaryIncrement
{

    public int intid { get; set; }

    public int fk_Empid { get; set; }

    public int intOldSalary { get; set; }

    public int intIncrementAmt { get; set; }

    public int intNetSalary { get; set; }

    public string vchUpby { get; set; }

    public System.DateTime dtUpdate { get; set; }

    public string vchUser { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
