
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblTitleMas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblTitleMas()
    {

        this.tblEmpAssesmentMas = new HashSet<tblEmpAssesmentMas>();

        this.tblEmpDetails = new HashSet<tblEmpDetails>();

        this.tblEmpMas = new HashSet<tblEmpMas>();

    }


    public int intid { get; set; }

    public string vchname { get; set; }

    public string vchcreatedby { get; set; }

    public System.DateTime dtcreated { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdate { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public Nullable<int> intcode { get; set; }

    public Nullable<int> intyr { get; set; }

    public Nullable<bool> IsSelected { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpAssesmentMas> tblEmpAssesmentMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpDetails> tblEmpDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpMas> tblEmpMas { get; set; }

}

}
