
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblTransferDetail
{

    public int intid { get; set; }

    public int fk_empid { get; set; }

    public string vchTransferFromBranch { get; set; }

    public string vchTransferToBranch { get; set; }

    public Nullable<System.DateTime> dtRelieved { get; set; }

    public Nullable<System.DateTime> dtTransferredDOJ { get; set; }

    public Nullable<int> intTransferSalary { get; set; }

    public Nullable<int> intRecievedSalary { get; set; }

    public string vchTransferBy { get; set; }

    public Nullable<System.DateTime> dtTransfer { get; set; }

    public string vchTransferHost { get; set; }

    public string vchTransferIP { get; set; }

    public string vchRecievedBy { get; set; }

    public Nullable<System.DateTime> dtRecieved { get; set; }

    public string vchRecievedHost { get; set; }

    public string vchRecievedIP { get; set; }

    public string vchTransferRemarks { get; set; }

    public string vchRecievedRemarks { get; set; }

    public bool BitCancel { get; set; }

    public string vchCancelReason { get; set; }

    public int fk_transferDept { get; set; }

    public int fk_TransferDesi { get; set; }

    public Nullable<int> fk_ReacievedDept { get; set; }

    public Nullable<int> fk_RecievedDesi { get; set; }

    public Nullable<int> intTransferredCode { get; set; }

    public Nullable<int> intRecievedCode { get; set; }

    public string vchOldEmpCode { get; set; }

    public int intTransferToCode { get; set; }

    public bool BitTransferComplete { get; set; }



    public virtual tblDeptMas tblDeptMas { get; set; }

    public virtual tblDesignationMas tblDesignationMas { get; set; }

    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
