
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblUserAuthorize
{

    public int intID { get; set; }

    public string vchUserName { get; set; }

    public Nullable<bool> bitAuthorization { get; set; }

    public Nullable<int> intSalaryfrom { get; set; }

    public Nullable<int> intSalaryTo { get; set; }

    public string vchcreatedby { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchipused { get; set; }

    public string vchhostname { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public string vchupdatedipdused { get; set; }

    public string vchupdatedhostname { get; set; }

    public int intcode { get; set; }

    public int intyr { get; set; }

}

}
