
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblUserLove
{

    public int intid { get; set; }

    public int fk_intUserId { get; set; }

    public bool BitMainAdmin { get; set; }

    public bool BitHrAdmin { get; set; }

    public bool BitOtherOption2 { get; set; }

    public bool BitOtherOption3 { get; set; }

    public bool BitOtherOption4 { get; set; }

    public int intcode { get; set; }

    public int intyr { get; set; }

    public bool IsVPHR { get; set; }

    public Nullable<System.DateTime> dtFromSession { get; set; }

    public bool bitNABHAccount { get; set; }



    public virtual tblUserMaster tblUserMaster { get; set; }

}

}
