
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblUserPermission
{

    public int intid { get; set; }

    public string fk_group { get; set; }

    public int fk_gpid { get; set; }

    public string fk_permissionname { get; set; }

    public string vchUserName { get; set; }

    public bool bitAllowed { get; set; }

    public int fk_Permissionid { get; set; }

    public Nullable<System.DateTime> dtCreated { get; set; }

    public string vchCreatedBy { get; set; }

    public string vchipused { get; set; }

    public string vchHostname { get; set; }

    public Nullable<System.DateTime> dtUpdated { get; set; }

    public string vchUpdatedBy { get; set; }

    public string vchUpdatedipused { get; set; }

    public string vchupdatedHostname { get; set; }

    public bool bitIsSelected { get; set; }

    public int intcode { get; set; }

    public int intyr { get; set; }



    public virtual tblGroupMaster tblGroupMaster { get; set; }

    public virtual tblPermissionMaster tblPermissionMaster { get; set; }

}

}
