
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblUserMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblUserMaster()
    {

        this.tblAssesmentQuestDetails = new HashSet<tblAssesmentQuestDetails>();

        this.tblConversation = new HashSet<tblConversation>();

        this.tblEmpAssesmentDetails = new HashSet<tblEmpAssesmentDetails>();

        this.tblJoiningRemarks = new HashSet<tblJoiningRemarks>();

        this.tblUserLove = new HashSet<tblUserLove>();

    }


    public int intid { get; set; }

    public string vchUsername { get; set; }

    public string Passcode { get; set; }

    public bool bitActive { get; set; }

    public string vchDepartment { get; set; }

    public Nullable<int> fk_intDeptid { get; set; }

    public string vchDesignation { get; set; }

    public Nullable<int> fk_intDesignationid { get; set; }

    public string vchMobile { get; set; }

    public bool bitAllowAssesment { get; set; }

    public string vchcreatedby { get; set; }

    public Nullable<System.DateTime> dtcreated { get; set; }

    public string vchhostname { get; set; }

    public string vchipused { get; set; }

    public string vchupdatedby { get; set; }

    public Nullable<System.DateTime> dtupdated { get; set; }

    public string vchupdatedhostname { get; set; }

    public string vchupdatedipused { get; set; }

    public int intcode { get; set; }

    public int intyr { get; set; }

    public string vchEmail { get; set; }

    public bool bitIsAllowLastAss { get; set; }

    public string vchProfilePath { get; set; }

    public string vchSignaturePath { get; set; }

    public string vchProfileName { get; set; }

    public string vchSignatureName { get; set; }

    public bool bitProfileComplete { get; set; }

    public bool bitSigComplete { get; set; }

    public Nullable<bool> bitISHOD { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAssesmentQuestDetails> tblAssesmentQuestDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConversation> tblConversation { get; set; }

    public virtual tblDeptMas tblDeptMas { get; set; }

    public virtual tblDesignationMas tblDesignationMas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmpAssesmentDetails> tblEmpAssesmentDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblJoiningRemarks> tblJoiningRemarks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblUserLove> tblUserLove { get; set; }

}

}
