
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblVPForward
{

    public int intid { get; set; }

    public int fk_EmpID { get; set; }

    public System.DateTime dtForwarded { get; set; }

    public string vchForwardBy { get; set; }

    public bool bitStatus { get; set; }

    public Nullable<System.DateTime> dtApproved { get; set; }

    public string vchApprovedBy { get; set; }

    public bool bitCancel { get; set; }



    public virtual tblEmpAssesmentMas tblEmpAssesmentMas { get; set; }

}

}
