
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HRM.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblYearMaster
{

    public System.Guid unID { get; set; }

    public string vchYearName { get; set; }

    public System.DateTime dtStartDate { get; set; }

    public System.DateTime dtEndDate { get; set; }

    public Nullable<bool> bitIsActive { get; set; }

}

}
